@baseUrl = http://localhost:1982

###

POST {{baseUrl}}/sessions/create 
Content-Type: application/json

{
    "sessionName": "matching maggot",
    "symbols": [
        "Amon Amarth",
        "Amorphis",
        "Anthrax",
        "Arch Enemy",
        "Bathory",
        "Behemoth",
        "Black Sabbath",
        "Blind Guardian",
        "Borknagar",
        "Cannibal Corpse",
        "Carcass",
        "Children of Bodom",
        "Cradle of Filth",
        "Dark Tranquillity",
        "Death",
        "Deicide",
        "Dimmu Borgir",
        "Dream Theater",
        "Eluveitie",
        "Emperor",
        "Ensiferum",
        "Enslaved",
        "Gojira",
        "HammerFall",
        "Harakiki for the Sky",
        "Iced Earth",
        "Immortal",
        "In Flames",
        "Iron Maiden",
        "Judas Priest",
        "Kreator",
        "Lamb of God",
        "Machine Head",
        "Manowar",
        "Marduk",
        "Mayhem",
        "Megadeth",
        "Metallica",
        "Morbid Angel",
        "Napalm Death",
        "Nightwish",
        "Obituary",
        "Opeth",
        "Overkill",
        "Pantera",
        "Sabaton",
        "Satyricon",
        "Sepultura",
        "Slayer",
        "Slipknot",
        "Sonata Arctica",
        "Stratovarius",
        "Suffocation",
        "System of a Down",
        "Testament",
        "Trivium",
        "Venom",
        "Watain"
    ]
}

###

POST {{baseUrl}}/sessions/join 
Content-Type: application/json

{
    "id": "8aab1f1f-0e8b-4de0-a9de-4b936a903442",
    "playerName": "phreakadelle"
}