@baseUrl = http://localhost:1982

###

POST {{baseUrl}}/session/create 
Content-Type: application/json

{
    "sessionName": "matching maggot",
    "symbols": [
        "Metallica",
        "Iron Maiden",
        "Slayer",
        "Megadeth",
        "Pantera",
        "Black Sabbath",
        "Judas Priest",
        "Lamb of God",
        "Slipknot",
        "System of a Down",
        "Sepultura",
        "Opeth",
        "Gojira",
        "Amon Amarth",
        "Trivium",
        "Behemoth",
        "Nightwish",
        "Children of Bodom",
        "Dream Theater",
        "Anthrax",
        "Testament",
        "Kreator",
        "Overkill",
        "Machine Head",
        "In Flames",
        "Arch Enemy",
        "Dark Tranquillity",
        "Dimmu Borgir",
        "Emperor",
        "Cradle of Filth",
        "Cannibal Corpse",
        "Morbid Angel",
        "Deicide",
        "Obituary",
        "Death",
        "Carcass",
        "Napalm Death",
        "Suffocation",
        "Amorphis",
        "Ensiferum",
        "Eluveitie",
        "Blind Guardian",
        "Iced Earth",
        "HammerFall",
        "Stratovarius",
        "Sonata Arctica",
        "Sabaton",
        "Manowar",
        "Venom",
        "Bathory",
        "Immortal",
        "Marduk",
        "Watain",
        "Mayhem",
        "Satyricon",
        "Enslaved",
        "Borknagar"
    ]
}

###

POST {{baseUrl}}/session/join 
Content-Type: application/json

{
    "id": "8aab1f1f-0e8b-4de0-a9de-4b936a903442",
    "playerName": "phreakadelle"
}