@baseUrl = http://localhost:1982/api

### Get session info

GET {{baseUrl}}/sessions/3cad4e60-0534-4fb0-9a80-1472bac569c2
Content-Type: application/json

### Join session

POST {{baseUrl}}/sessions/3cad4e60-0534-4fb0-9a80-1472bac569c2/join
Content-Type: application/json

{
    "playerName": "phreakadelle"
}

### Create preset session

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "sessionName": "test session",
    "preset": "uuid"
}

### Create custom session

POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "sessionName": "matching maggot",
    "symbols": [
        "Amon Amarth",
        "Amorphis",
        "Anthrax",
        "Arch Enemy",
        "Bathory",
        "Behemoth",
        "Black Sabbath",
        "Blind Guardian",
        "Borknagar",
        "Cannibal Corpse",
        "Carcass",
        "Children of Bodom",
        "Cradle of Filth",
        "Dark Tranquillity",
        "Death",
        "Deicide",
        "Dimmu Borgir",
        "Dream Theater",
        "Eluveitie",
        "Emperor",
        "Ensiferum",
        "Enslaved",
        "Gojira",
        "HammerFall",
        "Harakiki for the Sky",
        "Iced Earth",
        "Immortal",
        "In Flames",
        "Iron Maiden",
        "Judas Priest",
        "Kreator",
        "Lamb of God",
        "Machine Head",
        "Manowar",
        "Marduk",
        "Mayhem",
        "Megadeth",
        "Metallica",
        "Morbid Angel",
        "Napalm Death",
        "Nightwish",
        "Obituary",
        "Opeth",
        "Overkill",
        "Pantera",
        "Sabaton",
        "Satyricon",
        "Sepultura",
        "Slayer",
        "Slipknot",
        "Sonata Arctica",
        "Stratovarius",
        "Suffocation",
        "System of a Down",
        "Testament",
        "Trivium",
        "Venom",
        "Watain"
    ]
}